### ISSUE TITLE
Update user

### ISSUE THREAD

**Issue by vthayashi** [hedwig-project/authModule#3]
Como posso atualizar/corrigir dados do user? Por exemplo, se eu errar o email na hora de criar um usuário, eu posso corrigir?
Seria bom fazer o delete para user tbm (vi q já temos pra casa e módulos)

**Comment by gabimelo** [comment]
Normalmente eu nao costumo criar delete para muitas coisas nao. Usuario por exemplo: o dia que alguem quiser cancelar a conta, eu apenas mudo uma flag de `active` pra `False` . Primeiro por motivos de histórico (é interessante manter dados de usuários que um dia fizeram parte do sistema, mesmo que tenham optado por sair dele), segundo que em banco nao relacional, o delete de um usuario nao vai ligar se tem outros documentos referenciando esse usuario ou não, e aí pode dar erro em algum documento que ainda referecie um usuário não mais existente ao tentar acessá-lo

**Comment by vthayashi** [comment]
Verdade, então poderia ficar com essa flag, e criar o método update. Acho bom tratar erro do tipo usuário inexistente (não sei se já faz isso automaticamente)

**Comment by hugopossani** [comment]
Valeu Victor! Vou fazer o fix agora, e adicionar a flag de ativo. Nao entendi em relacao ao erro do usuario inexistente, em que caso? Se voce tentar autenticar com uma conta que nao existe, ela informa usuario/senha incorretos (de modo que a pessoa nao sabe qual dos dois que ocasionou o problema).

**Comment by vthayashi** [comment]
Ah blz, era essa mesma minha dúvida (Qdo tenta autenticar com conta q não existe)

**Comment by hugopossani** [comment]
@vthayashi essa issue foi resolvida junto com a #4. Apos o merge, vou colocar no servidor e vc da um signoff se estiver okay?
